### PR TITLE
add argument to print out linting errors

### PR DESCRIPTION
**Pull request by mcwhittemore**
I ran into some trouble trying to track down which line in a JSON file this was breaking on earlier today. @willwhite what do you think about adding a print argument for this?

### CODE REVIEW

**Comment by geohacker** [comment]
Me too! Spend like a reasonable amount of time :-/

**Comment by mcwhittemore** [comment]
Yea, I've been using this locally a bunch and it's really helped me.

Maybe @mapsam is up for a review?

**Comment by mapsam** [comment]
Just tested this out - works great @mcwhittemore!

screen shot 2016-07-26 at 5 38 42 pm

**Comment by mcwhittemore** [comment]
merged and published

**Comment by mapsam** [comment]
👏  thanks @mcwhittemore!

**Pull request merged**
